### PR TITLE
[HOPSWORKS-1380][featurestore] Configure Feature Group statistics during creation

### PR DESCRIPTION
**Pull request by moritzmeister**
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1380

### CODE REVIEW

**Comment by moritzmeister** [comment]
@steffengr review pls

**Comment by SirOibaf** [comment]
https://github.com/logicalclocks/hops-util/blob/6dca8816274fe84b08cf901b4205aee6569b6d9f/src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreUpdateFeaturegroupStats.java#L75 - This error message is misleading. We support updating and computing features for online featuregroups. Can you please fix it?

**Comment by SirOibaf** [comment]
https://github.com/logicalclocks/hops-util/blob/6dca8816274fe84b08cf901b4205aee6569b6d9f/src/main/java/io/hops/util/featurestore/ops/write_ops/FeaturestoreUpdateFeaturegroupStats.java#L81 - This cannot happen, as if it was a `ON_DEMAND_FEATURE_GROUP` an exception would have been thrown above

**Comment by moritzmeister** [comment]
https://github.com/logicalclocks/hops-util/pull/64#issuecomment-555113049
@SirOibaf 
I am not sure I understand you, this is about on demand feature groups and I haven't changed anything here. I don't see how it relates to online feature groups.

**Comment by moritzmeister** [comment]
https://github.com/logicalclocks/hops-util/pull/64#issuecomment-555113792
I see what you are saying, I can change it to a simple `false` and remove the `onDemand` variable. But the `getFeaturegroupDtoTypeStr` function is a helper that takes the boolean and is used in other places too.

**Comment by SirOibaf** [comment]
>  Or do you just mean the actual message should say something like: "... is only supported for cached and online feature groups.."

Yeah, I know you didn't touch it, but it cached my eye when I saw it. I'd say something like "Computing statistics is not supported for ondemand featuregroups"

**Comment by SirOibaf** [comment]
> [#64 (comment)](https://github.com/logicalclocks/hops-util/pull/64#issuecomment-555113792)
> I see what you are saying, I can change it to a simple `false` and remove the `onDemand` variable. But the `getFeaturegroupDtoTypeStr` function is a helper that takes the boolean and is used in other places too.

Yeah, that's what I meant. Don't change the method signature, just pass false there.

**Pull request merged**
